version: '3.8'

services:
  # Servicio principal para tests
  tests:
    build: .
    container_name: playwright-tests
    volumes:
      # Montar código fuente para desarrollo
      - .:/app
      # Excluir node_modules del host
      - /app/node_modules
      # Montar resultados para persistencia
      - ./results:/app/results
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run tests:e2e
    profiles:
      - e2e
      - all

  # Servicio para tests API
  tests-api:
    build: .
    container_name: playwright-api-tests
    volumes:
      - .:/app
      - /app/node_modules
      - ./results:/app/results
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run tests:api
    profiles:
      - api
      - all

  # Servicio para ejecutar todo el flujo
  flow:
    build: .
    container_name: playwright-flow
    volumes:
      - .:/app
      - /app/node_modules
      - ./results:/app/results
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run flow-tests
    profiles:
      - flow
      - all

  # Servicio para desarrollo interactivo
  dev:
    build: .
    container_name: playwright-dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./results:/app/results
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=development
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
    profiles:
      - dev

